### ISSUE TITLE
cloud :)

### ISSUE THREAD

**Issue by xxsle** [EliaFantini/APS-Aerial-Photography-Simulation-for-photogrammetric-flight-design#1]
hello :) hope you are well. i would appreciate it if you could share your data with me. thank u in advance..

**Comment by EliaFantini** [comment]
Hi, sorry for late reply, I was very busy last week. I'm afraid I don't have those files any more in my cloud, I will try to see if I still have them around in my local folders when I will have access to them

**Comment by xxsle** [comment]
I am grateful for your answer. I would really appreciate it if you could share the cloud with me. ps: I really love your work, but I have a few questions. can I ask you about them? if you are available

**Comment by EliaFantini** [comment]
Thank you! Sure ask me anything, but the project is from 2020 even though I uploaded it to GitHub later, so my memory about it is quite bad :(

**Comment by xxsle** [comment]
thank you, no problem :) you are using orthophoto+dem as input data. can we say true orthophoto for the output result? I also saw your output result, but I didn't understand what kind of result was obtained.  I mean, since there are no buildings etc., whether there are side facades or not, I could not grasp what kind of correction occurred in the output result :)

**Comment by EliaFantini** [comment]
No the output will not be an orthophoto. Actually this program is to go from an orthophoto to a normal photo. Basically with an orthopoto + dem as input data, you can say you have a 3d coloured model of the terrain, so a points cloud where each point has a colour, and also a geographical coordinates attached to it. Then you ca see my program as a sort of "raytracing" algorithm that renders images of this 3d model from whatever point of view and camera angle. This way you go from an orthophoto to a normal photo where projective rules are applied and therefore objects in the distance appear smaller and so on. In the 3d model there is a hill which is sligthly steep, and also a small building. In those points, as well as with plants, some 3d points will be missing as the scan is done from above so it doesn't see vertical points like the ones of a wall, but for them only one point is saved. Therefore some interpolation is needed to infer the value of those missing points. No AI is involved s it's quite limited. 
Here is an example of before and after interpolation (resampling), before interpolation color is present only where we have a point in the points cloud: 
<img width="718" alt="image" src="https://github.com/EliaFantini/APS-Aerial-Photography-Simulation-for-photogrammetric-flight-design/assets/62103572/0dcd1619-d507-4d46-913a-897b2445481c">

**Comment by xxsle** [comment]
I understand now. your work is really nice. i am actually trying to make a true orthophoto as an output result like your exe using my own dem data. so when looking at the orthophoto, all objects will be as if looking from the top. have you worked on this topic? can you give me ideas? i looked at github but they explained it very complicated :(

**Comment by EliaFantini** [comment]
I see, so you're tackling the inverse problem. Indeed it is much more complicated, but I'm afraid my code won't be very useful then as the processes to be applied are very different. I can't help you on that sorry

**Comment by xxsle** [comment]
I understand. I would still appreciate it if you could send me your data when you find it.

**Comment by EliaFantini** [comment]
Hi, I am very sorry but the files are not in my local folders too, I'm afraid I don't have them anymore

**Comment by EliaFantini** [comment]
Dear  @xxsle, eventually I found the data in my local folders, I uploaded it to google drive and put the link directly in the readme of this repository. Sorry for the delay, I hope it is still useful
